version: '3.3'
services:

  backserver:
    container_name: rpi_back_php73
    image: clemrz/raspi-api:prod
    build:
      context: ./
      args:
          ARCH: ${ARCH}
    volumes:
      - ./src:/var/www/html/
      - ./log:/var/log/
    ports:
      - ${HTTP_PORT}:80

  composer:
    container_name: ba_back_composer
    image: ${ARCH}composer:latest
    command: [ "composer", "install" ]
    volumes:
      - ./src:/app